### ISSUE TITLE
There Exists Some Security Issue 

### ISSUE THREAD

**Issue by vvbbnn00** [lyc8503/onedrive-cf-index-ng#11]
Hello, it seems that your project has the same security vulnerability as onedrive-vercel-index, which may lead to the leakage of the contents of your `.password` file. The image below is the proof of existence of the vulnerability.

![image](https://github.com/lyc8503/onedrive-cf-index-ng/assets/46409975/910cf387-c629-410d-867b-a6ab22aa71cc)

The specific content of the vulnerability can be found here. I have written a version that fixes the relevant security vulnerabilities. I hope it will be helpful to your project:
[https://github.com/vvbbnn00/onedrive-docker-index/blob/main/README_en.md#-security-issue-fixes](https://github.com/vvbbnn00/onedrive-docker-index/blob/main/README_en.md#-security-issue-fixes)

**Comment by lyc8503** [comment]
Hello, thank you for reporting the issue. I have confirmed that the first issue indeed exists, where one can bypass the password to access file contents directly through the ID obtained from the search box. I will fix this later.

The third issue was previously discovered by me and has already been fixed in commit e7eb86d.

As for the second issue, the AES_SECRET_KEY in oAuthHandler is actually only used to obfuscate the clientSecret (to prevent GitHub's credential leak detection from mistakenly sending warnings to users). The clientSecret of this project is originally public and shared, and the SECRET_KEY has been explicitly given in the documentation of onedrive-vercel-index, so I don't think this is a security issue.

**Comment by vvbbnn00** [comment]
@therockstarind  

Thank you for your reply.

Yes, if the AES_SECRET_KEY is solely used for obfuscating clientSecret, its leakage seems to not pose a significant issue (although exposing clientSecret is not a recommended practice).

However, the problem lies in the fact that with the leaked AES_SECRET_KEY, combined with issue 3, we can send a carefully crafted payload to the server, thereby causing destructive effects on the Workers KV content of the service.

I have noticed that you have made security improvements to the code that validates the incoming authCode, changing it to operate on the server side, which is excellent. However, the code that actually affects server data is located here:

https://github.com/lyc8503/onedrive-cf-index-ng/blob/e7eb86db5c435b2cc230097251eedbea3b197800/src/pages/api/index.ts#L162-L173

By utilizing the recently leaked AES_SECRET_KEY, we can encrypt some carefully designed content and then transmit it to the server via an API request, leading to the replacement of the server's access_token and refresh_token, causing service paralysis.

Here is an example:

This is the value in KV after initialization.
![image](https://github.com/lyc8503/onedrive-cf-index-ng/assets/46409975/bc929f0a-2778-4f7d-8689-a88e5c2a4d35)

Now, we construct content for replacement with the following code:

```js
const AES_SECRET_KEY = "onedrive-vercel-index"

console.log(CryptoJS.AES.encrypt("replaced", AES_SECRET_KEY).toString())
```

Then, we make a request through Postman.

![image](https://github.com/lyc8503/onedrive-cf-index-ng/assets/46409975/a683a546-13f9-49b7-8fce-017a26021509)

After completing the request, if we return to the KV page, we can see that the contents have been replaced, and the website service has accordingly crashed.

![image](https://github.com/lyc8503/onedrive-cf-index-ng/assets/46409975/65ab1ef2-2678-457a-8bc6-a49d859b5ef9)
![image](https://github.com/lyc8503/onedrive-cf-index-ng/assets/46409975/1d9df177-6efc-4049-8d20-338db75821ed)


Reviewing the entire security issue, it's not hard to see that the actual leakage of clientSecret is not important. The problem arose because we reused server-side security-related code on the client side. Therefore, I believe that the primary fix should be to avoid referencing the oAuthHandler.ts file on the frontend.

Of course, conducting a secondary verification of the content passed into the API is also a method to mitigate this vulnerability. Here is my proposed solution to the issue. In fact, I have chosen to abandon the operation of obfuscating and de-obfuscating the incoming access_token and refresh_token.

https://github.com/vvbbnn00/onedrive-docker-index/blob/ff39153255eb5d55c8388c0ace5cb409f45ef0dc/app/src/pages/api/index.ts#L404-L435

**Comment by lyc8503** [comment]
I'm sorry, thank you for pointing out the problem again. I previously overlooked the API in api/index used for actually uploading and saving the accessToken, my mistake 😂 I will fix this problem later.

Repeated practices seem to indicate that using a mixed front-end and back-end development approach in Next.js indeed leads to more and harder to spot security vulnerabilities. In the case of front-end and back-end separation in development, there will be no accidental leakage of server configurations and variables, and developers can more easily distinguish whether the verification logic should be written on the server or the client side.

**Comment by lyc8503** [comment]
Should have fixed the three issues you mentioned in commit 1709e1a and 50f32b8.
