### ISSUE TITLE
{"error":"Internal server error."}

### ISSUE THREAD

**Issue by churongcon** [lyc8503/onedrive-cf-index-ng#20]
{"error":"Internal server error."}
https://data-doctor-plus.pages.dev/api?path=/

**Comment by lyc8503** [comment]
Hello, please try to get the following error message from Cloudflare.

Specifically, open the https://dash.cloudflare.com/redirect?account=pages/view/onedrive-cf-index-ng page and click on it to view the details of your latest deployment. Start capturing the live logs in the Functions tab, at this point, open the page again to access the page with the error and you should be able to grab the latest logs.

**Comment by pengchangg** [comment]
我出现同样的报错，不过我是在访问 `protectedRoutes` 中定义的路由报错，我并不能在CF中看到你说的日志面板；
![image](https://github.com/user-attachments/assets/1c1f298f-c6dc-438c-a3bc-a7693a3d80cf)
![image](https://github.com/user-attachments/assets/bfb5a79c-7c9b-4f63-bd28-ecea2fbe81d7)
![image](https://github.com/user-attachments/assets/9591d84a-fb0a-468e-8481-a57b329c5d0a)
[部署地址](https://onedrive-cf-index-ng-eje.pages.dev)

**Comment by lyc8503** [comment]
@pengchangg 

你在 `Private` 文件夹下创建对应的密码文件了吗?

---

> 我并不能在CF中看到你说的日志面板

可能我说的不是非常清楚, 你应该是先点击你截图中的 “部署” 面板, 点击最新的一次部署右侧的查看详细信息.

<img width="1608" alt="image" src="https://github.com/user-attachments/assets/dd1acede-8457-4cd1-98eb-a5d7753e6197">

然后再点击函数 Tab, 往下翻才有一个实时日志的选项.

<img width="1333" alt="image" src="https://github.com/user-attachments/assets/756b2e56-a619-476a-9969-c04f35f4bd2f">

**Comment by wangwangit001** [comment]
{
  "truncated": false,
  "outcome": "ok",
  "scriptName": "pages-worker--3420200-production",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [
    {
      "message": [
        "TypeError: Cannot read properties of undefined (reading 'get')"
      ],
      "level": "error",
      "timestamp": 1723020501478
    }
  ],
  "eventTimestamp": 1723020501478,
  "event": {
    "request": {
      "url": "https://caec675f.onedrive-4b7.pages.dev/api?path=/",
      "method": "GET",
      "headers": {
        "accept": "application/json, text/plain, */*",
        "accept-encoding": "gzip, br",
        "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,en-GB;q=0.6",
        "cf-connecting-ip": "20.243.22.145",
        "cf-ipcountry": "JP",
        "cf-ray": "8af601d63d7fb009",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "dnt": "1",
        "host": "caec675f.onedrive-4b7.pages.dev",
        "priority": "u=1, i",
        "referer": "https://caec675f.onedrive-4b7.pages.dev/",
        "sec-ch-ua": "\"Chromium\";v=\"128\", \"Not;A=Brand\";v=\"24\", \"Microsoft Edge\";v=\"128\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0",
        "x-forwarded-proto": "https",
        "x-real-ip": "20.243.22.145"
      },
      "cf": {
        "clientTcpRtt": 1,
        "longitude": "139.68990",
        "httpProtocol": "HTTP/2",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 8075,
        "clientAcceptEncoding": "gzip, deflate, br, zstd",
        "country": "JP",
        "verifiedBotCategory": "",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsClientHelloLength": "1796",
        "tlsExportedAuthenticator": {
          "clientFinished": "2588a617f0a296dd8eabed9e6dadc31a4968b184befa1616721e676b044e7129",
          "clientHandshake": "248a4b473c9831b56c7a9c677b728be96a8a00ffc40023d31954fd6dac54c7d5",
          "serverHandshake": "4ae48282deedbeb5f4d17c8f4e6395cedaad4b2ed58450447349e54cc961ea10",
          "serverFinished": "3788feabf93fb558ccc3bc76f3dade89bcb3debb71473199050a52acae9adccf"
        },
        "tlsVersion": "TLSv1.3",
        "city": "Tokyo",
        "timezone": "Asia/Tokyo",
        "tlsClientExtensionsSha1": "NH+R0CGxFj4f6RfTzgvSF8kJFYk=",
        "region": "Tokyo",
        "edgeRequestKeepAliveStatus": 1,
        "requestPriority": "weight=220;exclusive=1",
        "latitude": "35.68930",
        "postalCode": "102-0082",
        "tlsClientRandom": "CGN0bBn7Bj+bNkwWY/RSSXMCQ478KtPA+GSuZ2uNA3M=",
        "regionCode": "13",
        "asOrganization": "Microsoft Azure",
        "colo": "NRT",
        "pagesHostName": "caec675f.onedrive-4b7.pages.dev",
        "botManagement": {
          "corporateProxy": false,
          "verifiedBot": false,
          "jsDetection": {
            "passed": false
          },
          "staticResource": false,
          "detectionIds": {},
          "score": 99
        }
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 2
}

**Comment by lyc8503** [comment]
@wangwangit001 

我看到你在仓库中修改了 clientId 和 obfuscatedClientSecret, 你可以尝试恢复默认的之后再试一次吗?

你为什么要使用自己的 clientId 和 clientSecret 呢, 我的文档中应该没有提到这个步骤, 你在大部分情况下应该也不需要这么做.

**Comment by wangwangit001** [comment]
@lyc8503 我用的是E5账号, 恢复之后可以进入授权界面了,但是授权的时候跳转到 http://localhost:9001/, 并没有出现code

**Comment by lyc8503** [comment]
> @lyc8503 我用的是E5账号, 恢复之后可以进入授权界面了,但是授权的时候跳转到 http://localhost:9001/, 并没有出现code

跳转到 http://localhost:9001/ 是正常的, URL 中没有 code 吗? 请你截图下授权后完整的页面.

**Comment by wangwangit001** [comment]
@lyc8503 可以了,非常感谢,刚刚应该是页面缓存的问题,我通过F12看到了请求, 刚刚填入这个code无法识别出来, 我刷新页面后正常了!

**Comment by lyc8503** [comment]
因长时间未回复关闭, 如仍有问题请携带日志 reopen.
