### ISSUE TITLE
安装向导完成后500错误

### ISSUE THREAD

**Issue by 2331892928** [lyc8503/onedrive-cf-index-ng#22]
<img width="1129" alt="image" src="https://github.com/lyc8503/onedrive-cf-index-ng/assets/69388528/4ce94c20-f86d-40d1-a1a6-31dad3d6c08f">

**Comment by lyc8503** [comment]
Please refer to https://github.com/lyc8503/onedrive-cf-index-ng/issues/20#issuecomment-2191510942 to get your log and attach it here.

**Comment by 2331892928** [comment]
[onedrive-cf-index-ng.19a81875-91ff-4c2c-8e5f-6cf26b1d7ed3.log](https://github.com/user-attachments/files/16177369/onedrive-cf-index-ng.19a81875-91ff-4c2c-8e5f-6cf26b1d7ed3.log)
这是最新的构建日志

**Comment by 2331892928** [comment]
> 请参阅[#20（评论）](https://github.com/lyc8503/onedrive-cf-index-ng/issues/20#issuecomment-2191510942)获取您的日志并将其附加到这里。

[onedrive-cf-index-ng.19a81875-91ff-4c2c-8e5f-6cf26b1d7ed3.log](https://github.com/user-attachments/files/16177369/onedrive-cf-index-ng.19a81875-91ff-4c2c-8e5f-6cf26b1d7ed3.log)
这是最新的构建日志

**Comment by lyc8503** [comment]
需要的不是构建日志（因为构建是成功的），是运行时抓取的日志。

另，请问你使用的是什么微软账号（个人，E5，世纪互联还是其他）？是否对配置文件做了什么修改？

**Comment by 2331892928** [comment]
> 需要的不是构建日志（因为构建是成功的），是运行时抓取的日志。
> 
> 另，请问你使用的是什么微软账号（个人，E5，世纪互联还是其他）？是否对配置文件做了什么修改？

我用的是E5，对api.config的clientId、obfuscatedClientSecret和site.config的userPrincipalName、title、baseDirectory、footer、protectedRoutes、email、links做了修改

**Comment by 2331892928** [comment]
> 需要的不是构建日志（因为构建是成功的），是运行时抓取的日志。
> 
> 另，请问你使用的是什么微软账号（个人，E5，世纪互联还是其他）？是否对配置文件做了什么修改？

请问在哪里看日志 能否给个图例 我实在没有找到

**Comment by lyc8503** [comment]
确实藏得比较隐蔽😂

你打开 https://dash.cloudflare.com/redirect?account=pages/view/onedrive-cf-index-ng ，点击最新的一次部署的查看详细信息

![image](https://github.com/lyc8503/onedrive-cf-index-ng/assets/36782264/e07f0faf-7ce6-4ccb-8ce3-df3718410909)

选择下面的函数，翻到下面可以看到实时日志，点击开始日志流，之后再开个新标签页访问你的网站，应该可以在日志流中看到你网站的错误日志

![image](https://github.com/lyc8503/onedrive-cf-index-ng/assets/36782264/84456ebc-e0ac-4d23-9020-b5bf9100e82f)

![image](https://github.com/lyc8503/onedrive-cf-index-ng/assets/36782264/aa25b845-3921-4456-9e48-1a9e9e71f5ac)

**Comment by 2331892928** [comment]
> 确实藏得比较隐蔽😂
> 
> 你打开 https://dash.cloudflare.com/redirect?account=pages/view/onedrive-cf-index-ng ，点击最新的一次部署的查看详细信息
> 
> ![image](https://private-user-images.githubusercontent.com/36782264/347860296-e07f0faf-7ce6-4ccb-8ce3-df3718410909.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODQwMTksIm5iZiI6MTcyMDc4MzcxOSwicGF0aCI6Ii8zNjc4MjI2NC8zNDc4NjAyOTYtZTA3ZjBmYWYtN2NlNi00Y2NiLThjZTMtZGYzNzE4NDEwOTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDExMjgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZWUxMjM1OTc1Mjk2YmI3ZTg4MGU3OTI1NTI0ODdkY2MyZGFhMDM0Y2FjMmIwMGZiM2Y3MTIyNzU5YzI4YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FzmyshsEbO-l_Rz13JGLHLGSFNp0lVdG3R5eP72dGUs)
> 
> 选择下面的函数，翻到下面可以看到实时日志，点击开始日志流，之后再开个新标签页访问你的网站，应该可以在日志流中看到你网站的错误日志
> 
> ![image](https://private-user-images.githubusercontent.com/36782264/347860594-84456ebc-e0ac-4d23-9020-b5bf9100e82f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODQwMTksIm5iZiI6MTcyMDc4MzcxOSwicGF0aCI6Ii8zNjc4MjI2NC8zNDc4NjA1OTQtODQ0NTZlYmMtZTBhYy00ZDIzLTkwMjAtYjViZjkxMDBlODJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDExMjgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZDBiNDRkODQ2ZmJiNTA5ZjY4OTY0OWM0MjBiODJlODllNDVkMjgwMWY2NDQ3NzZkN2JhMDQzMGRhNmY2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xRE7SNklDmp332fpfoWspWsNHOROSH-2D_Z1WrWVtT8)
> 
> ![image](https://private-user-images.githubusercontent.com/36782264/347861471-aa25b845-3921-4456-9e48-1a9e9e71f5ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODQwMTksIm5iZiI6MTcyMDc4MzcxOSwicGF0aCI6Ii8zNjc4MjI2NC8zNDc4NjE0NzEtYWEyNWI4NDUtMzkyMS00NDU2LTllNDgtMWE5ZTllNzFmNWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDExMjgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNmM1YTJjZDgxOTVlNTZiOGVhMzA0ZTUxZjk1ZDQzOGZhODVjMTZkMDI1YmNkNjBhYTUxNzM4ZDcwYzc5MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wjw_XOnUgOou-l6HoHqzgTB55rv0HZewgeVTZKeBGzI)

{
  "outcome": "ok",
  "scriptName": "pages-worker--3182847-production",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [
    {
      "message": [
        "0.AXEA04Pnmyqdw06UPvmD1BAMhKVzhiGm3VRMqddyb8HZTakBAAA.AgABBAIAAAApTwJmzXqdR4BN2miheQMYAgDs_wUA9P9YEPNYqaY_dN-ofyycYZWRMChJn77uoXvOmGplSAmo3tI_diKIxftPaxSa9d0ddu57gSw3vQuAYT-y0m-ewJ0C07SBHA3gK7BUFCYfJ_IQfXE663YwhjOfaYUf2ooSBwoad1ai9A0HpxwM1bHKmKGxkUpV2k0okAiBlV_TiH0j0qw87qjMHmzsCTcZz0W8Kp42OhoGlisfhM61UrBxBj8vXlrCAoZXlI9zAVO44P897OJPbJO0d24Pb1v0h_25gttnCQQzLiXu0JDjrAoyMreGPNgVLSBcFN5wbi26eNVMDPRZ21Y8eH8WyoWiyPqvk_6eQ4Pi4Qr6OfsGb8mX3gN_HIdYkWH7YE9VoZ9fi_YzmeSu_1sPmzlHI4oVNAYydLl0BiW1n22s1XEu2CnnsIDBYChSahhQ86AGlKfljS_sD6iuRlU_zPdQuzsxWxCYXY3t69cVeDrPRPWuC7LW9_tiI7TvKfssqnungBiBbBlO9j03xdSDk3gyNiQ48snax-xMYNOx82Sa5z3o2vu0eMtu0eJ_hiHZIx-68fp9xPoRvy--oeVLgvFTqRQ3L8EjVg67XZFKBtVvwhHYNGxXYucykAk89u7lYUXA9DFoBRqRyASqILh5VxSGxvO1vQJ2q1RNuCqw2ED8aVDEGlwG7esVvoI75Dt0yCzR3A"
      ],
      "level": "log",
      "timestamp": 1720783811005
    },
    {
      "message": [
        "TypeError: Cannot read properties of undefined (reading 'data')"
      ],
      "level": "error",
      "timestamp": 1720783811378
    }
  ],
  "eventTimestamp": 1720783811005,
  "event": {
    "request": {
      "url": "https://19a81875.onedrive-cf-index-ng-de6.pages.dev/onedrive-oauth/step-3?authCode=0.REDACTED.REDACTED",
      "method": "GET",
      "headers": {
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "accept-encoding": "gzip, br",
        "accept-language": "zh-CN,zh;q=0.9",
        "cf-connecting-ip": "43.224.6.194",
        "cf-ipcountry": "HK",
        "cf-ray": "8a20b322b8b2854d",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "dnt": "1",
        "host": "19a81875.onedrive-cf-index-ng-de6.pages.dev",
        "priority": "u=0, i",
        "referer": "https://19a81875.onedrive-cf-index-ng-de6.pages.dev/onedrive-oauth/step-2",
        "sec-ch-ua": "\"Not/A)Brand\";v=\"8\", \"Chromium\";v=\"126\", \"Google Chrome\";v=\"126\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\"",
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "same-origin",
        "sec-fetch-user": "?1",
        "sec-gpc": "1",
        "upgrade-insecure-requests": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        "x-forwarded-proto": "https",
        "x-real-ip": "43.224.6.194"
      },
      "cf": {
        "clientTcpRtt": 9,
        "longitude": "114.15010",
        "latitude": "22.29080",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 9381,
        "clientAcceptEncoding": "gzip, deflate, br, zstd",
        "country": "HK",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsExportedAuthenticator": {
          "clientFinished": "c7db9940f1a29624f5a35b6de777b2386303bde6a9a487d1efb59bd553416718",
          "clientHandshake": "b7887cdf1e18a30ca192c40b4101858f2da936400534389bbaca60e991554312",
          "serverHandshake": "71c2f37f16dfa232b5142a5846966a200eddcdf99eacd153a2d64ae4dc24cb86",
          "serverFinished": "b8601146e68447de14048fe0d9e40f055b4fe3d40988ee87f43797b166ba90e5"
        },
        "tlsVersion": "TLSv1.3",
        "colo": "HKG",
        "timezone": "Asia/Hong_Kong",
        "verifiedBotCategory": "",
        "tlsClientHelloLength": "1840",
        "edgeRequestKeepAliveStatus": 1,
        "requestPriority": "weight=256;exclusive=1",
        "tlsClientExtensionsSha1": "LE0KdbvIyebiNBSFu11FMmfgGS8=",
        "httpProtocol": "HTTP/2",
        "asOrganization": "Hong Kong Broadband Network",
        "tlsClientRandom": "FQxJB22u3W/oY73BNmZ74nb+u8x8jymvqG5m0Hr+LmU=",
        "pagesHostName": "19a81875.onedrive-cf-index-ng-de6.pages.dev",
        "botManagement": {
          "corporateProxy": false,
          "verifiedBot": false,
          "jsDetection": {
            "passed": false
          },
          "staticResource": false,
          "detectionIds": {},
          "score": 99
        }
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 1
}




{
  "outcome": "ok",
  "scriptName": "pages-worker--3182847-production",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [
    {
      "message": [
        "0.AXEA04Pnmyqdw06UPvmD1BAMhKVzhiGm3VRMqddyb8HZTakBAAA.AgABBAIAAAApTwJmzXqdR4BN2miheQMYAgDs_wUA9P9YEPNYqaY_dN-ofyycYZWRMChJn77uoXvOmGplSAmo3tI_diKIxftPaxSa9d0ddu57gSw3vQuAYT-y0m-ewJ0C07SBHA3gK7BUFCYfJ_IQfXE663YwhjOfaYUf2ooSBwoad1ai9A0HpxwM1bHKmKGxkUpV2k0okAiBlV_TiH0j0qw87qjMHmzsCTcZz0W8Kp42OhoGlisfhM61UrBxBj8vXlrCAoZXlI9zAVO44P897OJPbJO0d24Pb1v0h_25gttnCQQzLiXu0JDjrAoyMreGPNgVLSBcFN5wbi26eNVMDPRZ21Y8eH8WyoWiyPqvk_6eQ4Pi4Qr6OfsGb8mX3gN_HIdYkWH7YE9VoZ9fi_YzmeSu_1sPmzlHI4oVNAYydLl0BiW1n22s1XEu2CnnsIDBYChSahhQ86AGlKfljS_sD6iuRlU_zPdQuzsxWxCYXY3t69cVeDrPRPWuC7LW9_tiI7TvKfssqnungBiBbBlO9j03xdSDk3gyNiQ48snax-xMYNOx82Sa5z3o2vu0eMtu0eJ_hiHZIx-68fp9xPoRvy--oeVLgvFTqRQ3L8EjVg67XZFKBtVvwhHYNGxXYucykAk89u7lYUXA9DFoBRqRyASqILh5VxSGxvO1vQJ2q1RNuCqw2ED8aVDEGlwG7esVvoI75Dt0yCzR3A"
      ],
      "level": "log",
      "timestamp": 1720783810252
    },
    {
      "message": [
        "TypeError: Cannot read properties of undefined (reading 'data')"
      ],
      "level": "error",
      "timestamp": 1720783810815
    }
  ],
  "eventTimestamp": 1720783810250,
  "event": {
    "request": {
      "url": "https://19a81875.onedrive-cf-index-ng-de6.pages.dev/_next/data/REDACTED/onedrive-oauth/step-3.json?authCode=0.REDACTED.REDACTED",
      "method": "GET",
      "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip, br",
        "accept-language": "zh-CN,zh;q=0.9",
        "cf-connecting-ip": "43.224.6.194",
        "cf-ipcountry": "HK",
        "cf-ray": "8a20b31e0932854d",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "dnt": "1",
        "host": "19a81875.onedrive-cf-index-ng-de6.pages.dev",
        "priority": "u=1, i",
        "referer": "https://19a81875.onedrive-cf-index-ng-de6.pages.dev/onedrive-oauth/step-2",
        "sec-ch-ua": "\"Not/A)Brand\";v=\"8\", \"Chromium\";v=\"126\", \"Google Chrome\";v=\"126\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\"",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "sec-gpc": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        "x-forwarded-proto": "https",
        "x-nextjs-data": "1",
        "x-real-ip": "43.224.6.194"
      },
      "cf": {
        "clientTcpRtt": 5,
        "longitude": "114.15010",
        "latitude": "22.29080",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 9381,
        "clientAcceptEncoding": "gzip, deflate, br, zstd",
        "country": "HK",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsExportedAuthenticator": {
          "clientFinished": "c7db9940f1a29624f5a35b6de777b2386303bde6a9a487d1efb59bd553416718",
          "clientHandshake": "b7887cdf1e18a30ca192c40b4101858f2da936400534389bbaca60e991554312",
          "serverHandshake": "71c2f37f16dfa232b5142a5846966a200eddcdf99eacd153a2d64ae4dc24cb86",
          "serverFinished": "b8601146e68447de14048fe0d9e40f055b4fe3d40988ee87f43797b166ba90e5"
        },
        "tlsVersion": "TLSv1.3",
        "colo": "HKG",
        "timezone": "Asia/Hong_Kong",
        "verifiedBotCategory": "",
        "tlsClientHelloLength": "1840",
        "edgeRequestKeepAliveStatus": 1,
        "requestPriority": "weight=220;exclusive=1",
        "tlsClientExtensionsSha1": "LE0KdbvIyebiNBSFu11FMmfgGS8=",
        "httpProtocol": "HTTP/2",
        "asOrganization": "Hong Kong Broadband Network",
        "tlsClientRandom": "FQxJB22u3W/oY73BNmZ74nb+u8x8jymvqG5m0Hr+LmU=",
        "pagesHostName": "19a81875.onedrive-cf-index-ng-de6.pages.dev",
        "botManagement": {
          "corporateProxy": false,
          "verifiedBot": false,
          "jsDetection": {
            "passed": false
          },
          "staticResource": false,
          "detectionIds": {},
          "score": 99
        }
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 0
}

**Comment by 2331892928** [comment]
> 确实藏得比较隐蔽😂
> 
> 你打开 https://dash.cloudflare.com/redirect?account=pages/view/onedrive-cf-index-ng ，点击最新的一次部署的查看详细信息
> 
> ![image](https://private-user-images.githubusercontent.com/36782264/347860296-e07f0faf-7ce6-4ccb-8ce3-df3718410909.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzk5MzQsIm5iZiI6MTcyMTI3OTYzNCwicGF0aCI6Ii8zNjc4MjI2NC8zNDc4NjAyOTYtZTA3ZjBmYWYtN2NlNi00Y2NiLThjZTMtZGYzNzE4NDEwOTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA1MTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NGQ3NzEzMzZiNGViNzYyYmNiNWE3Mzc0MjI1NzczYTMyNTM3ZjBjOGEyYzgxNWQwOGZjY2M1NGIxYmU0OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ONOW8cWH56tmsMRYPEdcvulMzlLG1pt-5TxjFFGQmA4)
> 
> 选择下面的函数，翻到下面可以看到实时日志，点击开始日志流，之后再开个新标签页访问你的网站，应该可以在日志流中看到你网站的错误日志
> 
> ![image](https://private-user-images.githubusercontent.com/36782264/347860594-84456ebc-e0ac-4d23-9020-b5bf9100e82f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzk5MzQsIm5iZiI6MTcyMTI3OTYzNCwicGF0aCI6Ii8zNjc4MjI2NC8zNDc4NjA1OTQtODQ0NTZlYmMtZTBhYy00ZDIzLTkwMjAtYjViZjkxMDBlODJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA1MTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZTc5YmNmMzc5MTZiNWU5NTJhNzlhZTg0YzBkMDdkZjQ2ZGQyMWZlMWZiNDc5MDg5NGNkOTcyOTg5N2E2MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8CiZ3c_1Hr34oh1teFcfUmSr3rXmIk8k1WlI44Ay99w)
> 
> ![image](https://private-user-images.githubusercontent.com/36782264/347861471-aa25b845-3921-4456-9e48-1a9e9e71f5ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzk5MzQsIm5iZiI6MTcyMTI3OTYzNCwicGF0aCI6Ii8zNjc4MjI2NC8zNDc4NjE0NzEtYWEyNWI4NDUtMzkyMS00NDU2LTllNDgtMWE5ZTllNzFmNWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA1MTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5Y2E0MDlmNGIyODc5NGFlZDYyNjAzZGY5N2E5MDQxMTFlYTUzNTdjNzNkZjgzMTQ2YjkzMDk4ZGZlN2Y5MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UxyQL-HM7EKYWFoN8aIrO7jaNFysoIdogusvbdn3pfA)

看不出问题嘛？日志已经给了

**Comment by lyc8503** [comment]
抱歉，最近比较忙，可能不能及时回复所有问题。

初步观察似乎是微软的 API 返回了意料之外的结果，导致了问题。E5 用户应该不需要修改 clientId 和 secret，你是否能用默认的 ID 和 secret 重新部署后再登录试下。

你可以手动打开 https://pan.lyc8503.net/onedrive-oauth/step-1 页面重新进入认证流程。

**Comment by 2331892928** [comment]
> 抱歉，最近比较忙，可能不能及时回复所有问题。
> 
> 初步观察似乎是微软的 API 返回了意料之外的结果，导致了问题。E5 用户应该不需要修改 clientId 和 secret，你是否能用默认的 ID 和 secret 重新部署后再登录试下。
> 
> 你可以手动打开 https://yoursite.com/onedrive-oauth/step-1 页面重新进入认证流程。

可以使用了，以前我都是用的自己的clientId 和 secret，现在不行了，我应该怎么修改client权限以使用这个

**Comment by lyc8503** [comment]
> > 抱歉，最近比较忙，可能不能及时回复所有问题。
> > 初步观察似乎是微软的 API 返回了意料之外的结果，导致了问题。E5 用户应该不需要修改 clientId 和 secret，你是否能用默认的 ID 和 secret 重新部署后再登录试下。
> > 你可以手动打开 https://yoursite.com/onedrive-oauth/step-1 页面重新进入认证流程。
> 
> 可以使用了，以前我都是用的自己的clientId 和 secret，现在不行了，我应该怎么修改client权限以使用这个

可能你的以前的 clientId 过期了或者配置有误，无特殊情况完全无需自己配置 clientId。

如果你坚持要配置，请参考 https://ovi.swo.moe/docs/advanced#using-your-own-clientid-and-clientsecret-1
