### ISSUE TITLE
How to make multiple onedrive index?

### ISSUE THREAD

**Issue by spidy2356** [lyc8503/onedrive-cf-index-ng#28]
I already forked the project and configured everything on config.js but I want to make another Index for another onedrive account. So how can I do that?

I want to change header title, email, add telegram id etc. So it is possible to fork again or any other way?

One more question is, if the microsoft account doesn't have admin rights then it ask to validate during authentication. So how to do that?

**Comment by lyc8503** [comment]
> I want to change header title, email, add telegram id etc. So it is possible to fork again or any other way?

You can't fork a repo twice under one account/org. You may have to create another repo manually (using git) and create a new associated Cloudflare project.

> One more question is, if the microsoft account doesn't have admin rights then it ask to validate during authentication. So how to do that?

You have to validate that, If you don't have permission to authorize a 3rd-party app, then it's not possible to use this project. Maybe contact your org admin for help.

**Comment by spidy2356** [comment]
> You have to validate that, If you don't have permission to authorize a 3rd-party app, then it's not possible to use this project. Maybe contact your org admin for help.

I'm the admin, but I don't know how to validate for user accounts.

And yes, I can't fork but maybe import the project solve this issue ( one of my friend say it)

Thanks for the help

**Comment by lyc8503** [comment]
> I'm the admin, but I don't know how to validate for user accounts.

Maybe try this: https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/configure-user-consent?pivots=portal

As I don't know what subscription you're using, you may have to figure it out by yourself if the above docs doesn't work.
