### ISSUE TITLE
Multiple onedrive account single index

### ISSUE THREAD

**Issue by undeadmecha0** [lyc8503/onedrive-cf-index-ng#29]
Is it possible to index multiple accounts in one index?

**Comment by lyc8503** [comment]
No, it's impossible and probably won't be supported in near future.

**Comment by lyc8503** [comment]
You may have to setup multiple instances and add links to each other if you want to achieve this now.

**Comment by undeadmecha0** [comment]
Yes i made multiple individual instances but i was asking about if its possible to merge them into one?
So i can see all the files in multiple onedrive into a single list

**Comment by lyc8503** [comment]
> Yes i made multiple individual instances but i was asking about if its possible to merge them into one? So i can see all the files in multiple onedrive into a single list

This can increase the complexity quite a lot, so this is not planned in the near future.
