### ISSUE TITLE
build command exited with code: 1

### ISSUE THREAD

**Issue by noreplyzx** [lyc8503/onedrive-cf-index-ng#34]
[onedrive-index-ng.63c90c6f-8f04-4bc8-9503-f2e0dec18633.log](https://github.com/user-attachments/files/17929971/onedrive-index-ng.63c90c6f-8f04-4bc8-9503-f2e0dec18633.log)

**Comment by qingyuan0o0** [comment]
<html>
<body>

12:36:56.014 | ▲  Detected `pnpm-lock.yaml` version 6 generated by pnpm@8.x
-- | --
12:36:56.032 | ▲  Installing dependencies...
12:36:56.578 | ▲  Lockfile is up to date, resolution step is skipped
12:36:56.685 | ▲  Already up to date
12:36:58.011 | ▲
12:36:58.030 | ▲  Done in 1.8s
12:36:58.059 | ▲  Detected Next.js version: 13.5.4
12:36:58.080 | ▲  Running "pnpm run build"
12:36:58.514 | ▲  > onedrive-vercel-index@0.1.0 build /opt/buildhome/repo
12:36:58.514 | ▲  > next build
12:36:59.170 | ▲  Attention: Next.js now collects completely anonymous telemetry regarding usage.
12:36:59.170 | ▲  This information is used to shape Next.js' roadmap and prioritize features.
12:36:59.170 | ▲  You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
12:36:59.170 | ▲  https://nextjs.org/telemetry
12:36:59.254 | ▲  Linting and checking validity of types ...
12:37:04.537 | ▲  Failed to compile.
12:37:04.538 | ▲  ./src/components/Navbar.tsx:46:32
12:37:04.538 | ▲  Type error: Property 'forEach' does not exist on type 'string \| string[]'.
12:37:04.538 | ▲  Property 'forEach' does not exist on type 'string'.
12:37:04.538 | ▲
12:37:04.538 | ▲    44 \|     setIsOpen(false)
12:37:04.538 | ▲    45 \|
12:37:04.538 | ▲  > 46 \|     siteConfig.protectedRoutes.forEach(r => {
12:37:04.539 | ▲       \|                                ^
12:37:04.539 | ▲    47 \|       localStorage.removeItem(r)
12:37:04.539 | ▲    48 \|     })
12:37:04.540 | ▲    49 \|
12:37:04.577 | ▲  ELIFECYCLE  Command failed with exit code 1.
12:37:04.612 | ▲  Error: Command "pnpm run build" exited with 1
12:37:05.655 |  
12:37:05.655 | ⚡️ The Vercel build (`pnpm dlx vercel build`) command failed. For more details see the Vercel logs above.
12:37:05.655 | ⚡️ If you need help solving the issue, refer to the Vercel or Next.js documentation or their repositories.
12:37:05.656 |  
12:37:05.673 | Failed: Error while executing user command. Exited with error code: 1
12:37:05.683 | Failed: build command exited with code: 1
12:37:06.538 | Failed: error occurred while running build command


</body>
</html>
一步步根据教程设置失败了

**Comment by lyc8503** [comment]
This seems an incompatible change from one of the dependencies, Let me check it.

**Comment by lyc8503** [comment]
@noreplyzx @qingyuan0o0 This is a confirmed upstream issue: https://github.com/cloudflare/next-on-pages/issues/908, I have upgraded the dependency to fix this. 

However this introduce another issue https://github.com/cloudflare/next-on-pages/issues/544, You have to update the build command to `pnpm dlx @cloudflare/next-on-pages` on Dashboard like below, I will update the docs too.

![image](https://github.com/user-attachments/assets/5b04dd89-42d2-491d-8169-97df03f94223) 

Please try deploying again and it should work. Thanks for your report :)

**Comment by lyc8503** [comment]
> thank ! it working again

I found some other problems in build product, I ended up trying another workaround, now you don't need to update `build command`, just sync from my repo now.
