### ISSUE TITLE
Questions about security | 关于安全有些疑问

### ISSUE THREAD

**Issue by Mankvis** [lyc8503/onedrive-cf-index-ng#37]
1. 原始版本的 .password 貌似可以通过 token 拿到
2. [onedrive-index](https://github.com/iRedScarf/onedrive-index) 这个也是后继者（不过也停止维护了），里面提到了 
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/29cccf35-4718-42b8-a572-92a0a82c624b">

所以请问这个版本有改善吗

**Comment by lyc8503** [comment]
> 1. 原始版本的 .password 貌似可以通过 token 拿到

我不太明白这是什么意思，此程序中应该没有 token 的概念，token 就是明文的密码。目前版本中，如果你已经验证过密码，你可以访问密码文件。如果验证过后的用户复制 .password 的直链，那其他用户也可以访问。不过前提都是用户已知当前密码。

> 所以请问这个版本有改善吗

有的，本版本如果你使用环境变量配置 userPrincipalName，同样你的邮箱不会被暴露在前端。我也没有使用 NEXT_PUBLIC_ 开头的环境变量名，不会有提到的问题。

除了你提到的，我还修复了 https://github.com/lyc8503/onedrive-cf-index-ng/issues/11 中指出的两个安全问题。
