### ISSUE TITLE
关于pdf无法预览的问题

### ISSUE THREAD

**Issue by qingyuan0o0** [lyc8503/onedrive-cf-index-ng#39]
经过测试,打开pdf调用的是github.io的pdf.js,我的建议是使用 https://github.com/johannschopplich/pdfjs-serverless#-cloudflare-workers 实现,速度应该能提升很多,因为我尝试加载太久了,等了5分钟才打开一个pdf
如果能本地打开,体验应该会优化很多
![image](https://github.com/user-attachments/assets/c3c8b29a-931d-4f62-b4cb-334177310a19)

**Comment by lyc8503** [comment]
看到你这里加载一个 105 kB 的 JS 花费了 1.7 分钟, 很大概率是你的网络有问题(无法流畅访问互联网). 我这里使用时加载 PDF 时间正常. (2-3秒)

如果你的用户无法正常访问, 你可能需要考虑替换国内访问速度快的 JS CDN.

![image](https://github.com/user-attachments/assets/653bb55f-a737-4486-8d7d-03c21f81871a)

你提供的包是在 Workers 端解析 PDF, 此项目设计上并不需要在服务端解析 PDF.

**Comment by qingyuan0o0** [comment]
如何能够替换成国内源呢？配置文件中能配置吗？主要是加载github.io速度慢

**Comment by lyc8503** [comment]
配置文件中没有配置, 你需要在你自己的 Fork 中修改 https://github.com/lyc8503/onedrive-cf-index-ng/blob/main/src/components/previews/PDFPreview.tsx 这个文件中的地址, 将 mozilla.github.io 替换为某个对该站点的反向代理.

**Comment by qingyuan0o0** [comment]
好的谢谢我试试
