### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by imSamirOFFICIAL** [lyc8503/onedrive-cf-index-ng#4]
After doing everything as you said, still facing this error:

<p align="left"><img src="https://user-images.githubusercontent.com/52858312/281088758-e93dbfc1-8d38-4c47-bfa8-b5442803eaa7.png"width=70% height=70%></p>

**Comment by lyc8503** [comment]
Please try to get detailed logs from Cloudflare Dashboard (they have an online log stream) and attach them here so that I can figure out what's wrong.

**Comment by imSamirOFFICIAL** [comment]
No worries! Everything is working properly now. Please **DELETE** the issue. By the way, thanks! ❤️

**Comment by lyc8503** [comment]
Nice to hear that it's working for you. I'm deleting this issue for now.
