### ISSUE TITLE
Hide streaming link that detected

### ISSUE THREAD

**Issue by rrfqi** [lyc8503/onedrive-cf-index-ng#6]
![6545](https://github.com/lyc8503/onedrive-cf-index-ng/assets/35894106/c824e900-d76d-4402-88de-f9b42c7fd458)

I've set up a cf waf security for my custom domain by restricting outside my country, it did manage to block being downloaded from outside my country with the url from my custom domain, but it's still can be bypassed if they use the url from streaming link.
So is it possible to hide streaming link that detected from program like idm, 1dm, etc?

for example

this one is geo restricted
`https://69.696.org/api/raw?path=/Tentatiev%20Releases/TV%20Broadcast%20Archives/2023.02.26.Doraemon.UNCUT.720p.RCTI.HDTV.mkv `

this one isn't geo restricted
`https://696-my.sharepoint.com/personal/admin_696_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=aae318b9-e14b-4444-bce0-0b7f44e3d2d0&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvdGVudGF0aWV2LW15LnNoYXJlcG9pbnQuY29tQDJlNGY0Njk4LWY0NGYtNGI2My04YjVlLWI5NzNmYTI3NTAxYiIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE3MDI1MjE2MDciLCJleHAiOiIxNzAyNTI1MjA3IiwiZW5kcG9pbnR1cmwiOiJzUXVHL29icmQwOG80U285KzlKNk1EZVhFeEM3N1grMWVIb3FITXZqejhrPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTY0IiwiaXNsb29wYmFjayI6IlRydWUiLCJjaWQiOiI3TFJXZWxPUEpVMmNKMHc0NWFkN1RnPT0iLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiT1dOa01EazJNVFFkjkjhkjhgkjbnDBaVEUzTFRrd1pXWXRaamt5TVROaE16bG1PV1UyIiwiYXBwX2Rpc3BsYXluYW1lIjoib25lZHJpdmUtY2YtaW5kZXgtbmciLCJnaXZlbl9uYW1lIjoiZnVyb3N0eSIsInNpZ25pbl9zdGF0ZSI6IltcImttc2lcIl0iLCJhcHBpZCI6ImYyM2Y5OTE4LTE0YTUtNDZmMS05Zjc0LTEzZTU3MjczYjhmMyIsInRpZCI6IjJlNGY0Njk4LWY0NGYtNGI2My04YjVlLWI5NzNmYTI3NTAxYiIsInVwbiI6ImFkbWluQHRlbnRhdGlldi5vbm1pY3Jvc29mdC5jb20iLCJwdWlkIjoiMTAwMzIwMDMwM0E1MzVBNSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDMyMDAzMDNhNTM1YTVAopu2ZS5jb20iLCJzY3AiOiJhbGxmaWxlcy5yZWFkIGFsbHByb2ZpbGVzLnJlYWQiLCJ0dCI6IjIiLCJpcGFkZHIiOiIyMC4xOTAuMTYzLjI5In0.bPXrrQlJdmLlBDiUBH21W4LDOonv0rl9Djit57HJmBA&ApiVersion=2.0`

**Comment by lyc8503** [comment]
Your site is protected by Cloudflare WAF, but we're not directly serving files from your site. Instead, visitors are redirected to Microsoft to download the files. The second URL (`696-my.sharepoint.com`) you provided is managed by Microsoft and don't follow WAF rules.

However, the second link is temporary and can only be obtained via visiting your site. So if you already blocked visitors from other countries, they generally can't obtain the streaming link (unless they use a VPN) and access your files.

Generally speaking, this behaviour is expected and you don't have to worry about this in most cases.

**Comment by rrfqi** [comment]
oh you're right sorry I didn't think that far enough xD

**Comment by rrfqi** [comment]
btw, which option to display the dark mode?

**Comment by lyc8503** [comment]
> btw, which option to display the dark mode?

It should follow your system's setting and don't have an option to manually set it for now.
