### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by djsaikrishna** [lyc8503/onedrive-cf-index-ng#8]
Bring username password feature

**Comment by lyc8503** [comment]
What do you mean? Where do you want to use username and password? Please explain your feature request in detail.

**Comment by djsaikrishna** [comment]
> What do you mean? Where do you want to use username and password? Please explain your feature request in detail.

when i open my onedrive index it will ask user pass auth  like gdrive index   see  https://gitlab.com/GoogleDriveIndex/Google-Drive-Index

to secure my index and  when i share onedrive index file link to someone they will stream or download it but they  cant access my index  bcz of userpass auth, this feature usefull bro
add this feature also make it optional, those who need it they will use and those who dont need it they will skip it

i hope u understand 

thank you.

**Comment by lyc8503** [comment]
We already have the [Password Protected Folders](https://github.com/lyc8503/onedrive-cf-index-ng/wiki/Features#password-protected-folders) feature. That's similar to what you want.

It's already an optional feature, but it's a little different from what you're talking about in that you can't either list the file or download it directly via a link without a password, which is probably more in line with what most people would expect from a `password-protection` feature. (Controlling access via confidential URLs is usually insecure, the URLs themselves can easily be compromised in a variety of scenarios)

**Comment by djsaikrishna** [comment]
do u have telegram i will explain with example links

**Comment by lyc8503** [comment]
> do u have telegram i will explain with example links

Please just explain here so that everyone could see and discuss. If you have something you don't want to show publicly, please send them to my email address [me@lyc8503.site](mailto:me@lyc8503.site).
